# C?u h\uFFFDnh MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/apartment_management?sslmode=require
spring.datasource.username=root
spring.datasource.password=Dovantai123

# Hibernate - JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
